DROP TABLE IF EXISTS devices;

CREATE TABLE DEVICES (
  DEVICE_ID INT AUTO_INCREMENT  PRIMARY KEY,
  DEVICE_TYPE VARCHAR(250) NOT NULL,
  MAC_ADDRESS VARCHAR(250) NOT NULL,
  UPLINK_MAC_ADDRESS VARCHAR(250) DEFAULT NULL
);